apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/padm2/default
        mountPath: /secrets/default
      - kvPath: serviceuser/data/dev/srvpadm2
        mountPath: /secrets/serviceuser
  ingresses:
    - "https://padm2.nais.preprod.local"
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_PADM.INPUT
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_PADM
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.Q1_PADM.INPUT_BOQ
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.Q1_414.FS06_ARENA
    - name: PADM2_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/padm2
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: EIA_INBOUND_MOTTAK_QUEUE_NAME
      value: QA.Q414.FS06_EIA_MELDINGER
