apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  name: padm2-redis
  namespace: default
spec:
  image: navikt/secure-redis:5.0.3-alpine-2
  port: 6379
  vault:
    enabled: true
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  service:
    port: 6379