apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: padm2-alerts
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  groups:
    - name: padm2-alerts
      rules:
        - alert: PADM2-DOWN
          expr: kube_deployment_status_replicas_available{deployment="padm2"} == 0
          for: 30s
          annotations:
            consequence: Application is unavailable
            action: "Undersøk hvorfor pods er nede og få den kjørende igjen!"
            summary: "Det er ingen pods for app kjørende i namespace og dermed er appen nede."
          labels:
            namespace: teamsykefravr
            severity: critical
        - alert: PADM2-BACKOUT
          expr: sum(increase(padm2_message_sent_to_boq_total{app="padm2"} [1h])) > 0
          for: 5m
          annotations:
            consequence: PADM2 sendte melding til backout-queue
            action: "Undersøk om det er noe feil med meldingene som er persistert i databasen"
            summary: "Prosessering av minst 1 melding feilet og ble sendt til MQ backout queue."
          labels:
            namespace: teamsykefravr
            severity: danger
        - alert: PADM2-CRONJOB
          expr: sum(increase(padm2_messages_still_fail_after_1h_total{app="padm2"} [1h])) > 0
          for: 5m
          annotations:
            consequence: PADM2 cronjob klarer ikke å ferdigstille meldinger
            summary: "Prosessering av minst 1 melding feilet og ble ikke fullført selv om cronjob'en har forsøkt flere ganger"
          labels:
            namespace: teamsykefravr
            severity: danger
        - alert: PADM2-NO-MESSAGE
          expr: sum(increase(padm2_incoming_message_count_total{app="padm2"} [1h])) < 1 and (day_of_week() > 0 < 6 and hour() > 6 < 17)
          for: 5m
          annotations:
            consequence: PADM2 mottar ingen meldinger
            summary: "Ingen meldinger mottatt siste timen"
          labels:
            namespace: teamsykefravr
            severity: danger
