apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvpadm2
        mountPath: /secrets/serviceuser
      - kvPath: /azuread/data/prod/creds/padm2
        mountPath: /secrets/azuread/padm2
  webproxy: true
  ingresses:
    - "https://padm2.nais.adeo.no"
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_PADM.INPUT
    - name: MQ_HOST_NAME
      value: a01apvl271.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_PADM
    - name: AKTOR_REGISTER_V1_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp.adeo.no/nav-emottak-eletter-web/services/
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.P414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.P_PADM.INPUT_BOQ
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.nais.adeo.no/rest/journalpostapi/v1/journalpost
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.P414.AO01_SKJEMA_MOTTAK
    - name: PADM2_DB_URL
      value: jdbc:postgresql://A01DBVL009.adeo.no:5432/padm2
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: EIA_INBOUND_MOTTAK_QUEUE_NAME
      value: QA.P414.FS06_EIA_MELDINGER_FROM_PADM
    - name: PDF_GEN_URL
      value: https://padm2pdfgen.intern.nav.no/api/v1/genpdf/padm2/padm2
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: https://btsys.nais.adeo.no
    - name: OPPRETT_SAK_URL
      value: https://sak.nais.adeo.no/api/v1/saker
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.adeo.no
