apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvpadm2
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://padm2.nais.preprod.local"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  env:
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_PADM.INPUT
    - name: MQ_HOST_NAME
      value: b27apvl222.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS04
    - name: MQ_CHANNEL_NAME
      value: Q1_PADM
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.Q1_PADM.INPUT_BOQ
    - name: DOKARKIV_CLIENT_ID
      value: "972814f3-8bdf-44f8-a191-c2ed00020b54"
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.dev.intern.nav.no/rest/journalpostapi/v1/journalpost
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.Q1_414.AO01_SKJEMA_MOTTAK
    - name: PADM2_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/padm2
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: TOGGLE_DIALOGMELDINGER_TIL_KAFKA
      value: "true"
    - name: PDF_GEN_URL
      value: https://padm2pdfgen.dev.intern.nav.no/api/v1/genpdf/padm2/padm2
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: HELSENETT_CLIENT_ID
      value: dev-fss.teamsykmelding.syfohelsenettproxy
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: https://btsys.nais.preprod.local
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.preprod.local
    - name: STS_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
