apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: padm2
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - "https://padm2.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: padm2-db
        diskAutoresize: true
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "dokarkiv.prod-fss-pub.nais.io"
        - host: "syfohelsenettproxy.prod-fss-pub.nais.io"
        - host: "isproxy.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      tenant: nav.no
  envFrom:
    - secret: padm2-serviceuser
  kafka:
    pool: nav-prod
  env:
    - name: MQ_HOST_NAME
      value: a01apvl271.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_PADM
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_PADM.INPUT
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: QA.P_PADM.INPUT_BOQ
    - name: ARENA_OUTBOUND_QUEUENAME
      value: QA.P414.AO01_SKJEMA_MOTTAK
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.P414.IU03_UTSENDING
    - name: DOKARKIV_CLIENT_ID
      value: "162b3255-2f72-4399-8f7a-244add9ffaac"
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: PDF_GEN_URL
      value: https://padm2pdfgen.intern.nav.no/api/v1/genpdf/padm2/padm2
    - name: PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: PDL_ENDPOINT_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: HELSENETT_CLIENT_ID
      value: prod-fss.teamsykmelding.syfohelsenettproxy
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.prod-fss-pub.nais.io
    - name: LEGE_SUSPENSJON_CLIENT_ID
      value: prod-fss.teamsykefravr.isproxy
    - name: LEGE_SUSPENSJON_ENDPOINT_URL
      value: https://isproxy.prod-fss-pub.nais.io
    - name: KUHR_SAR_API_CLIENT_ID
      value: prod-fss.teamsykefravr.isproxy
    - name: KUHR_SAR_API_URL
      value: https://isproxy.prod-fss-pub.nais.io
